#!/bin/sh

chown system:android_input /sys/class/leds/led:torch_0/brightness
chown system:android_input /sys/class/leds/led:switch_0/brightness

chmod 666 /sys/class/leds/led:torch_0/brightness
chmod 666 /sys/class/leds/led:switch_0/brightness

while [ "$(getprop init.svc.perf-hal-2-2)" != "running" ]; do
    sleep 1
done

sleep 5
echo 1 > /proc/sys/kernel/sched_boost

echo ON > /dev/wlan

iw phy0 wowlan enable magic-packet disconnect
